GARFI/GARFI/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from GarfiApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='homepage'),
    url(r'^About/',include('GarfiApp.urls')),
]

GARFI/GarfiApp/urls.py
from django.conf.urls import url
from GarfiApp import views

app_name = 'GarfiApp'

urlpatterns = [
    url(r'^$',views.AboutPage.as_view(),name='aboutpage'),
    url(r'^SignUp/$',views.SignUp,name='signup_page'),
    url(r'^SignUp/Success/$',views.SignUpSuccess,name='signup_success'),
    url(r'^Login/$',views.LoginPage,name='loginpage'),
    url(r'^Login/UserHome/$',views.UserHome,name='user_home'),
    url(r'^Login/UserHome/InputCode/$',views.InputCode,name='inputcode'),
    url(r'^Login/UserHome/InputCode/SavePoints',views.SavePoints,name='save_points'),
]

GARFI/GarfiApp/models.py
from django.db import models
from django import forms
from django.urls import reverse
from django.http import HttpResponse

# Create your models here.
class UserAccount(models.Model):

    firstname = models.CharField(max_length=256)
    lastname = models.CharField(max_length=234)
    email = models.EmailField(max_length=234)
    mobilenumber = models.IntegerField()
    password = models.CharField(max_length=254)
    points = models.IntegerField()

    def __str__(self):

        return self.firstname


class Code(models.Model):

    code = models.CharField(max_length=11)

    def __str__(self):

        return self.code

GARFI/GarfiApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,View
from GarfiApp.models import UserAccount,Code
from django import forms
import random
# Create your views here.



class HomePage(TemplateView):

    template_name = 'GarfiApp/homepage.html'


class AboutPage(TemplateView):

    template_name = 'GarfiApp/aboutpage.html'

def SignUp(request):

    return render(request,"GarfiApp/signup_page.html")

def SignUpSuccess(request):
    user = UserAccount.objects.all()

    if request.method == "POST":
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        mobilenumber = request.POST.get('mobilenumber')
        password = request.POST.get('password')

        data = UserAccount.objects.create(firstname = firstname , lastname = lastname , email = email , mobilenumber = mobilenumber , password = password, points=0)
        data.save()


        return render(request,"GarfiApp/signup_success.html")


def LoginPage(request):

    return render (request, "GarfiApp/loginpage.html")

def UserHome(request):

    user = UserAccount.objects.all()

    if request.method == 'POST':
        global code
        code = ''.join([str(random.randint(0, 999)).zfill(3) for _ in range(2)])
        user = UserAccount.objects.all()
        data = Code.objects.create(code = str(code))
        data.save()
        print(code)

        email = request.POST.get('email')
        password = request.POST.get('password')

        for item in user:

            if item.email == email and item.password == password:


                break
        dict = {'email': email,'password':password,'firstname':item.firstname,'lastname':item.lastname,'points':item.points}
        return render (request,"GarfiApp/user_home.html", context = {'dict': dict, 'code':code} )



def InputCode(request):

    if request.method == 'POST':
        name = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        code = request.POST.get('code')
        user_details = {'name':name,'email':email,'password':password}


        return render(request,"GarfiApp/code.html", {'user': user_details,'code':code})

def SavePoints(request):

    if request.method == 'POST':

        user = UserAccount.objects.all()
        #data = Code.objects.all()

        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        input_code = request.POST.get('input-code')


        for item in user:

            if (item.email == email and item.password == password):
                print('SavePoints')
                print(code)
                print(name)
                print(email)
                print(password)

                if input_code == code:
                    item.points += 10
                    cond = True
                    item.save()
                    Code.objects.all().delete()
                    break
                else:

                    cond=False
                    break

        if cond == True:
            return render(request,"GarfiApp/save_points.html", {'cond':True})
        else:
            return render(request,"GarfiApp/save_points.html", {'cond':False})



# def CodeVer(request):
#
#     cloudcode = Code.objects.all()
#     if request.method == 'POST':
#
#         code = request.POST.get('code')
#
#         if cloudcode.code == code:
#
#             return HttpResponse("Codes match!")








# class LoginPage(View):
#
#     pass

GARFI/GarfiApp/templates/GarfiApp/aboutpage.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}

<div class="jumbotron">
  <h2>About Page</h2>

</div>

{% endblock  %}

GARFI/GarfiApp/templates/GarfiApp/basepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>GarFi Systems</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">GarFi Smart Bin Systems</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'GarfiApp:aboutpage' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'GarfiApp:signup_page' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'GarfiApp:loginpage' %}">Login</a>
            </li>

          </ul>

        </div>
      </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

GARFI/GarfiApp/templates/GarfiApp/code.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}

  <h2>Please enter your code here </h2><br>
<div class="jumbotron">
  <form  action="{% url 'GarfiApp:save_points' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="name" value="{{user.name}}">
    <input type="hidden" name="email" value="{{user.email}}">
    <input type="hidden" name="password" value="{{user.password}}">
    <input type="hidden" name="code" value="{{code}}">
    <input type="text" name="input-code" placeholder="Enter Code">
    <input type="submit" class="btn btn-outline-danger"  name="" value="Add Points">

  </form>

  <script type="text/javascript">
    alert("Your code is {{code}}")
  </script>
</div>





{% endblock  %}

GARFI/GarfiApp/templates/GarfiApp/homepage.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to GarFi Smart Bin Systems</h1>

  </div>
  <div class="container">
    <h3>Gar Fi?</h3>
    <p class = "HomePageIdea">
      Want something in return as you bin?
      <br>

      Well, stuff GarFi with waste and plastics... it loves it!! <br>

      GarFi would reward you with Wifi!!!


    </p>

  </div>



{% endblock %}

GARFI/GarfiApp/templates/GarfiApp/loginpage.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}

<form action="{% url 'GarfiApp:user_home' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email"  name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">Please enter your Email</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Enter your password">
  </div>

  <button type="submit" class="btn btn-outline-dark">Log In</button>
</form>


{% endblock %}

GARFI/GarfiApp/templates/GarfiApp/save_points.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}


{% block body_block %}
<div class="jumbotron">

  {% if cond %}

    <h1>Points got added!</h1>
    <h2>Thank you for using Garfi</h2>
    <a href="{% url 'homepage' %}" class="btn btn-outline-warning" >Return back to Home!</a>

  {% else %}
  <h4>Invalid Code! Please try again!</h4>

  {% endif %}

</div>


{% endblock %}

GARFI/GarfiApp/templates/GarfiApp/signup_page.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}
<form action="{% url 'GarfiApp:signup_success' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label>First Name:</label>
    <input type="text" class="form-control" name="firstname" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">Please enter your First Name</small>
  </div>
  <div class="form-group">
    <label>Last Name:</label>
    <input type="text" class="form-control" name="lastname" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">Please enter your Last Name</small>
  </div>
  <div class="form-group">
    <label>Email ID:</label>
    <input type="email" class="form-control" name="email" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">Please enter your Email ID</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password:</label>
    <input type="password" class="form-control" name="password" id="exampleInputPassword1">
  </div>
  <div class="form-group">
    <label>Mobile Number:</label>
    <input type="number" class="form-control" name="mobilenumber" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">Please enter your Mobile Number</small>
  </div>
  <button type="submit" class="btn btn-success">Sign Up</button>
</form>



{% endblock  %}

GARFI/GarfiApp/templates/GarfiApp/signup_success.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}
  <h1>Signed Up Successfully</h1>
  <a class="btn btn-success" href="{% url 'homepage' %}">Home!</a>
{% endblock  %}

GARFI/GarfiApp/templates/GarfiApp/user_home.html
<!DOCTYPE html>
{% extends "GarfiApp/basepage.html" %}

{% block body_block %}
    <form action="{% url 'GarfiApp:inputcode' %}"  method="post">
      {% csrf_token %}


    <div class="jumbotron">

        <h1>Logged in successfully!</h1>
        <h2>Welcome {{ dict.firstname }} {{ dict.lastname }}</h2><br>
        <input type="hidden" name="email" value="{{dict.email}}">
        <input type="hidden" name="password" value="{{dict.password}}">
        <input type="hidden" name="username" value="{{dict.firstname}}">
        <input type="hidden" name="code" value="{{code}}">
        <h3> Available points: {{ dict.points }} </h3>

    </div>
    <input type="submit" class="btn btn-outline-primary " name="" value="Collect Points">
    </form>

{% endblock %}